#!/bin/bash
set -e

_HOSTNAME=${VIRTUAL_HOST:-$(hostname)}

echo " * nginx: server_name ${_HOSTNAME}"
sed -i -r "s/example.com/${_HOSTNAME}/g" /etc/nginx/sites-enabled/default-ssl.conf
sed -i -r "s/example.com/${_HOSTNAME}/g" /etc/nginx/sites-enabled/default.conf

mkdir -p /tmp/sites-enabled
cp /etc/nginx/sites-enabled/*.conf /tmp/sites-enabled

if [ "${SSL_ENABLED}" = "false" ] ; then
	# SSL disabled
	rm /etc/nginx/sites-enabled/default-ssl.conf
else
	# SSL enabled
	if [ ! -f /etc/nginx/sites-enabled/default-ssl.conf ]; then
		cp /tmp/sites-enabled/default-ssl.conf /etc/nginx/sites-enabled
	fi

	if [ ! -f /etc/nginx/ssl/${_HOSTNAME}.dhparam.pem ] ; then
		# Generate Diffie Hellman parameter file, as the default shipped with Ubuntu is 1024bits and considered insecure
		# https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_handshake_and_dhparam
		echo " * nginx:  Generating /etc/nginx/ssl/${_HOSTNAME}.dhparam.pem"
		export RANDFILE=/app/.rnd
		rm -f $RANDFILE
		openssl dhparam -out /etc/nginx/ssl/${_HOSTNAME}.dhparam.pem 2048
	fi

	if [ ! -f /etc/nginx/ssl/${_HOSTNAME}.key ] ; then
		# Generate a self signed certificate if one does not exist
		# Expires in 365 days
		echo " * nginx:  Generating default /etc/nginx/ssl/${_HOSTNAME}.key /etc/nginx/ssl/${_HOSTNAME}.crt"
		openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/ssl/${_HOSTNAME}.key -out /etc/nginx/ssl/${_HOSTNAME}.crt -nodes -days 365 -subj "/C=US/ST=State/L=Location/O=/OU=/CN=localdomain"
	fi
fi

# Set worker_processes = num cpu cores
procs=$(cat /proc/cpuinfo |grep processor | wc -l)
if [[ "$procs" > "${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}" ]]; then
	# number of available processor cores exceeds the maximum permitted, limit to maximum
	echo " * nginx:  Using max ${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES} of $procs available cores"
	procs=${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}
fi

echo " * nginx:  worker_processes = $procs"
sed -i -r "s/worker_processes\s+[0-9]+/worker_processes $procs/" /etc/nginx/nginx.conf

echo " * nginx:  client_max_body_size = ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE}"
sed -i -r "s/client_max_body_size.+M;/client_max_body_size ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE};/" /etc/nginx/nginx.conf

exec nginx