#!/bin/bash
set -e

sed -i -r "s/example.com/${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}/g" /etc/nginx/sites-enabled/default-ssl.conf
sed -i -r "s/example.com/${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}/g" /etc/nginx/sites-enabled/default.conf

if [ ! -f /etc/nginx/ssl/${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}.dhparam.pem ] ; then
	# Generate Diffie Hellman parameter file, as the default shipped with Ubuntu is 1024bits and considered insecure
	# https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_handshake_and_dhparam
	echo " * nginx:  Generating default DH parameters for ${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}"
	export RANDFILE=/app/.rnd
	rm -f $RANDFILE
	openssl dhparam -out /etc/nginx/ssl/${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}.dhparam.pem 2048
fi

# Generate a self signed certificate if one does not exist
# Expires in 365 days
if [ ! -f /etc/nginx/ssl/${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}.key ] ; then
	echo " * nginx:  Generating RSA keypair for ${VIRTUAL_HOST:-$DEFAULT_VIRTUAL_HOST}"
	openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/ssl/${VIRTUAL_HOST}.key -out /etc/nginx/ssl/${VIRTUAL_HOST-$DEFAULT_VIRTUAL_HOST}.crt -nodes -days 365 -subj "/C=Country/ST=State/L=Location/O=/OU=/CN=localdomain"
fi


# Set worker_processes = num cpu cores
procs=$(cat /proc/cpuinfo |grep processor | wc -l)
if [[ "$procs" > "${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}" ]]; then
	# number of available processor cores exceeds the maximum permitted, limit to maximum
	echo " * nginx:  use maximum ${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES} of $procs available cores"
	procs=${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}
fi

echo " * nginx:  worker_processes = $procs"
sed -i -r "s/worker_processes\s+[0-9]+/worker_processes $procs/" /etc/nginx/nginx.conf

echo " * nginx:  client_max_body_size = ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE}"
sed -i -r "s/client_max_body_size.+M;/client_max_body_size ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE};/" /etc/nginx/nginx.conf

exec nginx