#!/bin/bash
set -e

if [ ! -f /etc/nginx/ssl/dhparam.pem ] ; then
	# https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_handshake_and_dhparam
	echo "Generating default DH parameters"
	openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
fi

exec nginx