#!/usr/bin/env bash

sed "s@__BACKEND_ADDRESS__@${VARNISH_BACKEND_ADDRESS}@" </etc/varnish/default.vcl.source >/etc/varnish/default.vcl
sed -i "s@__BACKEND_PORT__@${VARNISH_BACKEND_PORT}@" /etc/varnish/default.vcl
sed -i "s@__BACKEND_HOSTNAME__@${VARNISH_BACKEND_HOSTNAME}@" /etc/varnish/default.vcl
sed -i "s@__PROBE_INTERVAL__@${VARNISH_PROBE_INTERVAL}@" /etc/varnish/default.vcl
sed -i "s@__PROBE_TIMEOUT__@${VARNISH_PROBE_TIMEOUT}@" /etc/varnish/default.vcl
sed -i "s@__GRACE_TIME__@${VARNISH_GRACE_TIME}@" /etc/varnish/default.vcl

exec varnishd -F -f ${VARNISH_VCL_FILE} -s malloc,${VARNISH_MEMORY} -a 0.0.0.0:${VARNISH_LISTEN_PORT}
