#!/usr/bin/env bash

for name in VARNISH_BACKEND_PORT VARNISH_BACKEND_HOST
do
    eval value=\$$name
    sed -i "s|{${name}}|${value}|g" /etc/varnish/default.vcl
done

varnishd -f /etc/varnish/default.vcl -s malloc,${VARNISH_MEMORY} -a 0.0.0.0:${VARNISH_PORT}

exec varnishlog
