#!/bin/bash

# =============================================================================
# 	NGINX
# =============================================================================

set -e

# set nginx user
echo " * nginx:  user ${APP_USER:-$DEFAULT_APP_USER}"
sed -i -r "s/user\s+[a-z]+;$/user ${APP_USER:-$DEFAULT_APP_USER};/" /etc/nginx/nginx.conf

# worker_processes = num cpu cores
procs=$(cat /proc/cpuinfo |grep processor | wc -l)
if [[ "$procs" > "${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}" ]]; then
	echo " * nginx:  use maximum ${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES} of $procs available cores"
	procs=${NGINX_MAX_WORKER_PROCESSES:-$DEFAULT_NGINX_MAX_WORKER_PROCESSES}
fi

echo " * nginx:  worker_processes = $procs"
sed -i -r "s/worker_processes\s+[0-9]+/worker_processes $procs/" /etc/nginx/nginx.conf

echo " * nginx:  client_max_body_size = ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE}"
sed -i -r "s/client_max_body_size.+M;/client_max_body_size ${UPLOAD_MAX_SIZE:-$DEFAULT_UPLOAD_MAX_SIZE};/" /etc/nginx/nginx.conf

if [ ! -f /etc/nginx/ssl/dhparam.pem ] ; then
	# https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_handshake_and_dhparam
	echo " * nginx:  generating /etc/nginx/ssl/dhparam.pem ..."
	mkdir -p /etc/nginx/ssl
	export RANDFILE=/root/.rnd
	rm -f $RANDFILE
	openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
fi

exec nginx