name: Action Lint
on: [pull_request]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          reporter: "github-pr-review"
