name: AutoMySQLBackup Lint Dockerfile
on:
  pull_request:
    branches:
      - main
    paths:
      - "automysqlbackup/**"
jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: automysqlbackup
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: "Dockerfile"
